---
title: "Comparacion Modelos Var1p"
author: "Juan Pedro Lopez Marin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
resultado_modelo_tbag_conzv_svml = readRDS("modelo_tbag_conzv_svml_var1p")
resultado_modelo_tbag_conzv_svmr = readRDS("modelo_tbag_conzv_svmr_var1p")
resultado_modelo_tbag_conzv_svmp = readRDS("modelo_tbag_conzv_svmp_var1p")
resultado_modelo_tbag_conzv_rf = readRDS("modelo_tbag_conzv_rf_var1p")
resultado_modelo_tbag_conzv_nb = readRDS("modelo_tbag_conzv_nb_var1p")
resultado_modelo_tbag_sinzv_svml = readRDS("modelo_tbag_sinzv_svml_var1p")
resultado_modelo_tbag_sinzv_svmr = readRDS("modelo_tbag_sinzv_svmr_var1p")
resultado_modelo_tbag_sinzv_svmp = readRDS("modelo_tbag_sinzv_svmp_var1p")
resultado_modelo_tbag_sinzv_rf = readRDS("modelo_tbag_sinzv_rf_var1p")
resultado_modelo_tbag_sinzv_nb = readRDS("modelo_tbag_sinzv_nb_var1p")
resultado_modelo_tbag_sinneuro_svml = readRDS("modelo_tbag_sinneuro_svml_var1p")
resultado_modelo_tbag_sinneuro_svmr = readRDS("modelo_tbag_sinneuro_svmr_var1p")
resultado_modelo_tbag_sinneuro_svmp = readRDS("modelo_tbag_sinneuro_svmp_var1p")
resultado_modelo_tbag_sinneuro_rf = readRDS("modelo_tbag_sinneuro_rf_var1p")
resultado_modelo_tbag_sinneuro_nb = readRDS("modelo_tbag_sinneuro_nb_var1p")
resultado_modelo_lda_conzv_svml = readRDS("modelo_lda_conzv_svml_var1p")
resultado_modelo_lda_conzv_svmr = readRDS("modelo_lda_conzv_svmr_var1p")
resultado_modelo_lda_conzv_svmp = readRDS("modelo_lda_conzv_svmp_var1p")
resultado_modelo_lda_conzv_rf = readRDS("modelo_lda_conzv_rf_var1p")
resultado_modelo_lda_conzv_nb = readRDS("modelo_lda_conzv_nb_var1p")
resultado_modelo_lda_sinzv_svml = readRDS("modelo_lda_sinzv_svml_var1p")
resultado_modelo_lda_sinzv_svmr = readRDS("modelo_lda_sinzv_svmr_var1p")
resultado_modelo_lda_sinzv_svmp = readRDS("modelo_lda_sinzv_svmp_var1p")
resultado_modelo_lda_sinzv_rf = readRDS("modelo_lda_sinzv_rf_var1p")
resultado_modelo_lda_sinzv_nb = readRDS("modelo_lda_sinzv_nb_var1p")
resultado_modelo_lda_sinneuro_svml = readRDS("modelo_lda_sinneuro_svml_var1p")
resultado_modelo_lda_sinneuro_svmr = readRDS("modelo_lda_sinneuro_svmr_var1p")
resultado_modelo_lda_sinneuro_svmp = readRDS("modelo_lda_sinneuro_svmp_var1p")
resultado_modelo_lda_sinneuro_rf = readRDS("modelo_lda_sinneuro_rf_var1p")
resultado_modelo_lda_sinneuro_nb = readRDS("modelo_lda_sinneuro_nb_var1p")
resultado_modelo_nb_conzv_svml = readRDS("modelo_nb_conzv_svml_var1p")
resultado_modelo_nb_conzv_svmr = readRDS("modelo_nb_conzv_svmr_var1p")
resultado_modelo_nb_conzv_svmp = readRDS("modelo_nb_conzv_svmp_var1p")
resultado_modelo_nb_conzv_rf = readRDS("modelo_nb_conzv_rf_var1p")
resultado_modelo_nb_conzv_nb = readRDS("modelo_nb_conzv_nb_var1p")
resultado_modelo_nb_sinzv_svml = readRDS("modelo_nb_sinzv_svml_var1p")
resultado_modelo_nb_sinzv_svmr = readRDS("modelo_nb_sinzv_svmr_var1p")
resultado_modelo_nb_sinzv_svmp = readRDS("modelo_nb_sinzv_svmp_var1p")
resultado_modelo_nb_sinzv_rf = readRDS("modelo_nb_sinzv_rf_var1p")
resultado_modelo_nb_sinzv_nb = readRDS("modelo_nb_sinzv_nb_var1p")
resultado_modelo_nb_sinneuro_svml = readRDS("modelo_nb_sinneuro_svml_var1p")
resultado_modelo_nb_sinneuro_svmr = readRDS("modelo_nb_sinneuro_svmr_var1p")
resultado_modelo_nb_sinneuro_svmp = readRDS("modelo_nb_sinneuro_svmp_var1p")
resultado_modelo_nb_sinneuro_rf = readRDS("modelo_nb_sinneuro_rf_var1p")
resultado_modelo_nb_sinneuro_nb = readRDS("modelo_nb_sinneuro_nb_var1p")
resultado_modelo_rf_conzv_svml = readRDS("modelo_rf_conzv_svml_var1p")
resultado_modelo_rf_conzv_svmr = readRDS("modelo_rf_conzv_svmr_var1p")
resultado_modelo_rf_conzv_svmp = readRDS("modelo_rf_conzv_svmp_var1p")
resultado_modelo_rf_conzv_rf = readRDS("modelo_rf_conzv_rf_var1p")
resultado_modelo_rf_conzv_nb = readRDS("modelo_rf_conzv_nb_var1p")
resultado_modelo_rf_sinzv_svml = readRDS("modelo_rf_sinzv_svml_var1p")
resultado_modelo_rf_sinzv_svmr = readRDS("modelo_rf_sinzv_svmr_var1p")
resultado_modelo_rf_sinzv_svmp = readRDS("modelo_rf_sinzv_svmp_var1p")
resultado_modelo_rf_sinzv_rf = readRDS("modelo_rf_sinzv_rf_var1p")
resultado_modelo_rf_sinzv_nb = readRDS("modelo_rf_sinzv_nb_var1p")
resultado_modelo_rf_sinneuro_svml = readRDS("modelo_rf_sinneuro_svml_var1p")
resultado_modelo_rf_sinneuro_svmr = readRDS("modelo_rf_sinneuro_svmr_var1p")
resultado_modelo_rf_sinneuro_svmp = readRDS("modelo_rf_sinneuro_svmp_var1p")
resultado_modelo_rf_sinneuro_rf = readRDS("modelo_rf_sinneuro_rf_var1p")
resultado_modelo_rf_sinneuro_nb = readRDS("modelo_rf_sinneuro_nb_var1p")
```


```{r}
objetos = list(
  tbag_conzv_svml = resultado_modelo_tbag_conzv_svml,
  tbag_conzv_svmr = resultado_modelo_tbag_conzv_svmr,
  tbag_conzv_svmp = resultado_modelo_tbag_conzv_svmp,
  tbag_conzv_rf = resultado_modelo_tbag_conzv_rf,
  tbag_conzv_nb = resultado_modelo_tbag_conzv_nb,
  tbag_sinzv_svml = resultado_modelo_tbag_sinzv_svml,
  tbag_sinzv_svmr = resultado_modelo_tbag_sinzv_svmr,
  tbag_sinzv_svmp = resultado_modelo_tbag_sinzv_svmp,
  tbag_sinzv_rf = resultado_modelo_tbag_sinzv_rf,
  tbag_sinzv_nb = resultado_modelo_tbag_sinzv_nb,
  tbag_sinneuro_svml = resultado_modelo_tbag_sinneuro_svml,
  tbag_sinneuro_svmr = resultado_modelo_tbag_sinneuro_svmr,
  tbag_sinneuro_svmp = resultado_modelo_tbag_sinneuro_svmp,
  tbag_sinneuro_rf = resultado_modelo_tbag_sinneuro_rf,
  tbag_sinneuro_nb = resultado_modelo_tbag_sinneuro_nb,
  lda_conzv_svml = resultado_modelo_lda_conzv_svml,
  lda_conzv_svmr = resultado_modelo_lda_conzv_svmr,
  lda_conzv_svmp = resultado_modelo_lda_conzv_svmp,
  lda_conzv_rf = resultado_modelo_lda_conzv_rf,
  lda_conzv_nb = resultado_modelo_lda_conzv_nb,
  lda_sinzv_svml = resultado_modelo_lda_sinzv_svml,
  lda_sinzv_svmr = resultado_modelo_lda_sinzv_svmr,
  lda_sinzv_svmp = resultado_modelo_lda_sinzv_svmp,
  lda_sinzv_rf = resultado_modelo_lda_sinzv_rf,
  lda_sinzv_nb = resultado_modelo_lda_sinzv_nb,
  lda_sinneuro_svml = resultado_modelo_lda_sinneuro_svml,
  lda_sinneuro_svmr = resultado_modelo_lda_sinneuro_svmr,
  lda_sinneuro_svmp = resultado_modelo_lda_sinneuro_svmp,
  lda_sinneuro_rf = resultado_modelo_lda_sinneuro_rf,
  lda_sinneuro_nb = resultado_modelo_lda_sinneuro_nb,
  nb_conzv_svml = resultado_modelo_nb_conzv_svml,
  nb_conzv_svmr = resultado_modelo_nb_conzv_svmr,
  nb_conzv_svmp = resultado_modelo_nb_conzv_svmp,
  nb_conzv_rf = resultado_modelo_nb_conzv_rf,
  nb_conzv_nb = resultado_modelo_nb_conzv_nb,
  nb_sinzv_svml = resultado_modelo_nb_sinzv_svml,
  nb_sinzv_svmr = resultado_modelo_nb_sinzv_svmr,
  nb_sinzv_svmp = resultado_modelo_nb_sinzv_svmp,
  nb_sinzv_rf = resultado_modelo_nb_sinzv_rf,
  nb_sinzv_nb = resultado_modelo_nb_sinzv_nb,
  nb_sinneuro_svml = resultado_modelo_nb_sinneuro_svml,
  nb_sinneuro_svmr = resultado_modelo_nb_sinneuro_svmr,
  nb_sinneuro_svmp = resultado_modelo_nb_sinneuro_svmp,
  nb_sinneuro_rf = resultado_modelo_nb_sinneuro_rf,
  nb_sinneuro_nb = resultado_modelo_nb_sinneuro_nb,
  rf_conzv_svml = resultado_modelo_rf_conzv_svml,
  rf_conzv_svmr = resultado_modelo_rf_conzv_svmr,
  rf_conzv_svmp = resultado_modelo_rf_conzv_svmp,
  rf_conzv_rf = resultado_modelo_rf_conzv_rf,
  rf_conzv_nb = resultado_modelo_rf_conzv_nb,
  rf_sinzv_svml = resultado_modelo_rf_sinzv_svml,
  rf_sinzv_svmr = resultado_modelo_rf_sinzv_svmr,
  rf_sinzv_svmp = resultado_modelo_rf_sinzv_svmp,
  rf_sinzv_rf = resultado_modelo_rf_sinzv_rf,
  rf_sinzv_nb = resultado_modelo_rf_sinzv_nb,
  rf_sinneuro_svml = resultado_modelo_rf_sinneuro_svml,
  rf_sinneuro_svmr = resultado_modelo_rf_sinneuro_svmr,
  rf_sinneuro_svmp = resultado_modelo_rf_sinneuro_svmp,
  rf_sinneuro_rf = resultado_modelo_rf_sinneuro_rf,
  rf_sinneuro_nb = resultado_modelo_rf_sinneuro_nb
)
```



```{r}
resultados_df <- data.frame()

for (nombre in names(objetos)){
  objeto <- objetos[[nombre]]
  
  # Extraer y ordenar los resultados por precisión
  mejor_resultado <- objeto$results[order(objeto$results$Accuracy, decreasing = TRUE), ][1,c("Accuracy","Kappa")]
  
  # Añadir el método/algoritmo utilziado en cada caso
  mejor_resultado = c("Algoritmo" = objeto$method,mejor_resultado)
  
  # Añadir los valores de los hiperparámetros
  combinacion_hiperparametros = paste(names(objeto$bestTune), objeto$bestTune, sep = "=", collapse = ", ")
  mejor_resultado = c(mejor_resultado, "Hiperparametros" = combinacion_hiperparametros)
  
  # Añadir la varianza total acumulada y el mínimo de conteo de variantes para cada caso
  mejor_resultado = c(mejor_resultado, "Condiciones" = nombre)
  
  # Añadir la fila al dataframe final
  resultados_df = rbind(resultados_df, mejor_resultado)
  
}
# Ver el dataframe resultante
resultados_df[order(resultados_df$Accuracy, decreasing = TRUE),]
```







# Comparación de modelos con datos de test


## Comparación de los resultados con 3 clases con todas las variables

```{r}
categoria_muestras = read.csv(file = "samples.csv", sep = "\t")

variantes_5pc = read.csv2(file = "dataset2_5pc.csv", sep = "\t")
variantes_5pc$grupo = categoria_muestras$class
variantes_5pc$grupo = as.factor(variantes_5pc$grupo)
rownames(variantes_5pc) = variantes_5pc[,1]
variantes_5pc = variantes_5pc[,-1]


variantes_5pc = variantes_5pc %>%
    select(last_col(), everything())

```


```{r}
resultados_test_df <- data_frame(
  Algoritmo = character(),
  Precisión = numeric(),
  Sens_Cardio = numeric(),
  Sens_Hemato = numeric(),
  Sens_Neuro = numeric(),
  Espec_Cardio = numeric(),
  Espec_Hemato = numeric(),
  Espec_Neuro = numeric(),
  Hiperparametros = character(),
  Condiciones = character()
)

for (nombre in names(objetos)){
  set.seed(1234)

  objeto = objetos[[nombre]]
  
  parametros_model <-  unlist(strsplit(nombre, split = "_"))
  
  if (parametros_model[1] == "tbag"){
    parametros_model[1] = "treebag"
  }
  
  if (parametros_model[2] == "sinneuro"){
    next
  }
  
  if (parametros_model[2] == "conzv"){
    next
  }
  
  
  resultado_rfe = readRDS(paste0('resultado_rfe_',parametros_model[1],'_6000_',parametros_model[2]))
  
  variantes_5pc_reducido = variantes_5pc[,c(predictors(resultado_rfe),"grupo")]
  
  set.seed(1234)

  particion_2 = createDataPartition(variantes_5pc_reducido$grupo, p=0.85, list = FALSE)
  train_data = variantes_5pc_reducido[particion_2,]
  test_data = variantes_5pc_reducido[-particion_2,]
  
   # Realizar predicción
  set.seed(1234)
  prediccion <- predict(objeto, newdata = test_data)
  
  # Calcular matriz de confusión
  set.seed(1234)
  matriz_conf <- confusionMatrix(prediccion, test_data$grupo)
  
  # Combinación de hiperparámetros
  combinacion_hiperparametros <- paste(names(objeto$bestTune), objeto$bestTune, sep = "=", collapse = ", ")
  
  # Métricas de calidad
  
  metricas_calidad <- c(
    round(as.numeric(matriz_conf$overall["Accuracy"][[1]]), 4),
    round(as.numeric(matriz_conf$byClass["Class: cardio","Sensitivity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: hemato","Sensitivity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: neuro_muscular","Sensitivity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: cardio","Specificity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: hemato","Specificity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: neuro_muscular","Specificity"]), 4)
    )
  
  
  
  # Crear fila a insertar
  fila_a_insertar <- c(
    objeto$method,
    metricas_calidad,
    combinacion_hiperparametros,
    nombre
  )
  

  resultados_test_df <- bind_rows(resultados_test_df, data_frame(
    Algoritmo = fila_a_insertar[1],
    Precisión = as.numeric(fila_a_insertar[2]),
    Sens_Cardio = as.numeric(fila_a_insertar[3]),
    Sens_Hemato = as.numeric(fila_a_insertar[4]),
    Sens_Neuro = as.numeric(fila_a_insertar[5]),
    Espec_Cardio = as.numeric(fila_a_insertar[6]),
    Espec_Hemato = as.numeric(fila_a_insertar[7]),
    Espec_Neuro = as.numeric(fila_a_insertar[8]),
    Hiperparametros = fila_a_insertar[9],
    Condiciones = fila_a_insertar[10]
  ))
  
}

saveRDS(resultados_test_df, "resultados_comparacion_3class_var1p")

resultados_test_df[order(resultados_test_df$Precisión, decreasing = TRUE),]
```
```{r}
comparacion_3clases = readRDS("resultados_comparacion_3class_var1p")
comparacion_3clases[order(comparacion_3clases$Precisión, decreasing = TRUE),]
```


# Comparación de los resultados con 3 clases y sin variables con var = 0

```{r}
resultados_test_df <- data_frame(
  Algoritmo = character(),
  Precisión = numeric(),
  Sens_Cardio = numeric(),
  Sens_Hemato = numeric(),
  Sens_Neuro = numeric(),
  Espec_Cardio = numeric(),
  Espec_Hemato = numeric(),
  Espec_Neuro = numeric(),
  Hiperparametros = character(),
  Condiciones = character()
)

for (nombre in names(objetos)){
  set.seed(1234)

  objeto = objetos[[nombre]]
  
  parametros_model <-  unlist(strsplit(nombre, split = "_"))
  
  if (parametros_model[1] == "tbag"){
    parametros_model[1] = "treebag"
  }
  
  if (parametros_model[2] == "sinneuro"){
    next
  }
  
  if (parametros_model[2] == "sinzv"){
    next
  }
  
  
  resultado_rfe = readRDS(paste0('resultado_rfe_',parametros_model[1],'_6000_',parametros_model[2]))
  
  variantes_5pc_reducido = variantes_5pc[,c(predictors(resultado_rfe),"grupo")]
  
  set.seed(1234)

  particion_2 = createDataPartition(variantes_5pc_reducido$grupo, p=0.85, list = FALSE)
  train_data = variantes_5pc_reducido[particion_2,]
  test_data = variantes_5pc_reducido[-particion_2,]
  
   # Realizar predicción
  set.seed(1234)
  prediccion <- predict(objeto, newdata = test_data)
  
  # Calcular matriz de confusión
  set.seed(1234)
  matriz_conf <- confusionMatrix(prediccion, test_data$grupo)
  
  # Combinación de hiperparámetros
  combinacion_hiperparametros <- paste(names(objeto$bestTune), objeto$bestTune, sep = "=", collapse = ", ")
  
  # Métricas de calidad
  
  metricas_calidad <- c(
    round(as.numeric(matriz_conf$overall["Accuracy"][[1]]), 4),
    round(as.numeric(matriz_conf$byClass["Class: cardio","Sensitivity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: hemato","Sensitivity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: neuro_muscular","Sensitivity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: cardio","Specificity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: hemato","Specificity"]), 4),
    round(as.numeric(matriz_conf$byClass["Class: neuro_muscular","Specificity"]), 4)
    )
  
  
  
  # Crear fila a insertar
  fila_a_insertar <- c(
    objeto$method,
    metricas_calidad,
    combinacion_hiperparametros,
    nombre
  )
  

  resultados_test_df <- bind_rows(resultados_test_df, data_frame(
    Algoritmo = fila_a_insertar[1],
    Precisión = as.numeric(fila_a_insertar[2]),
    Sens_Cardio = as.numeric(fila_a_insertar[3]),
    Sens_Hemato = as.numeric(fila_a_insertar[4]),
    Sens_Neuro = as.numeric(fila_a_insertar[5]),
    Espec_Cardio = as.numeric(fila_a_insertar[6]),
    Espec_Hemato = as.numeric(fila_a_insertar[7]),
    Espec_Neuro = as.numeric(fila_a_insertar[8]),
    Hiperparametros = fila_a_insertar[9],
    Condiciones = fila_a_insertar[10]
  ))
  
}

saveRDS(resultados_test_df, "resultados_comparacion_3class_conzv_var1p")

resultados_test_df[order(resultados_test_df$Precisión, decreasing = TRUE),]
```


```{r}
comparacion_3clases_conzv = readRDS("resultados_comparacion_3class_conzv_var1p")
comparacion_3clases_conzv[order(comparacion_3clases_conzv$Precisión, decreasing = TRUE),]
```



# Comparación de los resultados con 2 clases

```{r}
variantes_5pc = read.csv2(file = "dataset2_5pc.csv", sep = "\t")
variantes_5pc$grupo = categoria_muestras$class
variantes_5pc = variantes_5pc[variantes_5pc$grupo != "neuro_muscular", ]
variantes_5pc$grupo = as.factor(variantes_5pc$grupo)
rownames(variantes_5pc) = variantes_5pc[,1]
variantes_5pc = variantes_5pc[,-1]


variantes_5pc = variantes_5pc %>%
    select(last_col(), everything())
```






```{r}
objetos2 = list(
  tbag_sinneuro_svml = resultado_modelo_tbag_sinneuro_svml,
  tbag_sinneuro_svmr = resultado_modelo_tbag_sinneuro_svmr,
  tbag_sinneuro_svmp = resultado_modelo_tbag_sinneuro_svmp,
  tbag_sinneuro_rf = resultado_modelo_tbag_sinneuro_rf,
  tbag_sinneuro_nb = resultado_modelo_tbag_sinneuro_nb,
  lda_sinneuro_svml = resultado_modelo_lda_sinneuro_svml,
  lda_sinneuro_svmr = resultado_modelo_lda_sinneuro_svmr,
  lda_sinneuro_svmp = resultado_modelo_lda_sinneuro_svmp,
  lda_sinneuro_rf = resultado_modelo_lda_sinneuro_rf,
  lda_sinneuro_nb = resultado_modelo_lda_sinneuro_nb,
  nb_sinneuro_svml = resultado_modelo_nb_sinneuro_svml,
  nb_sinneuro_svmr = resultado_modelo_nb_sinneuro_svmr,
  nb_sinneuro_svmp = resultado_modelo_nb_sinneuro_svmp,
  nb_sinneuro_rf = resultado_modelo_nb_sinneuro_rf,
  nb_sinneuro_nb = resultado_modelo_nb_sinneuro_nb,
  rf_sinneuro_svml = resultado_modelo_rf_sinneuro_svml,
  rf_sinneuro_svmr = resultado_modelo_rf_sinneuro_svmr,
  rf_sinneuro_svmp = resultado_modelo_rf_sinneuro_svmp,
  rf_sinneuro_rf = resultado_modelo_rf_sinneuro_rf,
  rf_sinneuro_nb = resultado_modelo_rf_sinneuro_nb
)
```


```{r}
# Crear un data frame vacío para almacenar los resultados
resultados_test_2class <- data_frame(
  Algoritmo = character(),
  Precisión = numeric(),
  Sensibilidad = numeric(),
  Especificidad = numeric(),
  Hiperparametros = character(),
  Condiciones = character()
)

# Verificar que el archivo RDS existe antes de leerlo
for (nombre in names(objetos2)){
  set.seed(1234)
  
  objeto = objetos2[[nombre]]
  
  parametros_model <-  unlist(strsplit(nombre, split = "_"))
  
  if (parametros_model[1] == "tbag"){
    parametros_model[1] = "treebag"
  }
  
  # Nombre del archivo RDS a leer
  rds_file <- paste0('resultado_rfe_', parametros_model[1], '_6000_', parametros_model[2])
  cat("Leyendo el archivo:", rds_file, "\n")
  
  # Verificar que el archivo existe
  if (!file.exists(rds_file)) {
    cat("Archivo no encontrado:", rds_file, "\n")
    next
  }
  
  # Leer el archivo RDS
  resultado_rfe <- readRDS(rds_file)
  
  # Filtrar los datos
  variantes_5pc_reducido <- variantes_5pc[, c(predictors(resultado_rfe), "grupo")]
  
  set.seed(1234)
  particion_2 <- createDataPartition(variantes_5pc_reducido$grupo, p = 0.85, list = FALSE)
  train_data <- variantes_5pc_reducido[particion_2,]
  test_data <- variantes_5pc_reducido[-particion_2,]
  
  # Realizar predicción
  set.seed(1234)
  prediccion <- predict(objeto, newdata = test_data)
  
  # Calcular matriz de confusión
  set.seed(1234)
  matriz_conf <- confusionMatrix(prediccion, test_data$grupo)
  
  # Combinación de hiperparámetros
  combinacion_hiperparametros <- paste(names(objeto$bestTune), objeto$bestTune, sep = "=", collapse = ", ")
  
  # Métricas de calidad
  metricas_calidad <- c(
    round(as.numeric(matriz_conf$overall["Accuracy"][[1]]), 4),
    round(as.numeric(matriz_conf$byClass["Sensitivity"][[1]]), 4),
    round(as.numeric(matriz_conf$byClass["Specificity"][[1]]), 4)
  )
  
  # Crear fila a insertar
  fila_a_insertar <- c(
    objeto$method,
    metricas_calidad,
    combinacion_hiperparametros,
    nombre
  )
  
  resultados_test_2class <- bind_rows(resultados_test_2class, data_frame(
    Algoritmo = fila_a_insertar[1],
    Precisión = as.numeric(fila_a_insertar[2]),
    Sensibilidad = as.numeric(fila_a_insertar[3]),
    Especificidad = as.numeric(fila_a_insertar[4]),
    Hiperparametros = fila_a_insertar[5],
    Condiciones = fila_a_insertar[6]
  ))
}

saveRDS(resultados_test_2class, "resultados_comparacion_2class_var1p")
```

```{r}
comparacion_2clases = readRDS("resultados_comparacion_2class_var1p")
comparacion_2clases[order(comparacion_2clases$Especificidad, decreasing = TRUE),]

```














# Heatmap con 3 clases y todas las variantes

```{r}
comparacion_3clases = readRDS("resultados_comparacion_3class_var1p")
```

```{r}
var1p_3class_heatmap = comparacion_3clases[,c(2,3,4,5,6,7,8,10)]
var1p_3class_heatmap
var1p_3class_heatmap = as.data.frame(var1p_3class_heatmap)
rownames(var1p_3class_heatmap) = var1p_3class_heatmap$Condiciones
var1p_3class_heatmap = var1p_3class_heatmap[,-8]
var1p_3class_heatmap = as.matrix(var1p_3class_heatmap)
```

```{r}
library(ggplot2)
library(grid)
library(pheatmap)



crear_heatmap <- function(matriz, color_palette, main_title, filename) {
    # Crear el heatmap
    heatmap <- pheatmap(matriz, 
                        cluster_rows = TRUE,
                        cluster_cols = TRUE,
                        treeheight_row = 0,    # Ocultar dendograma de filas
                        treeheight_col = 0,    # Ocultar dendograma de columnas
                        show_rownames = TRUE,
                        fontsize_col = 10,
                        angle_col = 90,        # Rotar nombres de columnas 45 grados
                        color = color_palette,
                        main = main_title)
    
    # Guardar el heatmap como PNG
    ggsave(filename, plot = heatmap, device = "png")
    
    # Retornar el objeto heatmap (opcional)
    return(heatmap)
}

colores_heatmap <- colorRampPalette(c("dodgerblue3","white", "firebrick1"))(50)

```

```{r}
crear_heatmap(var1p_3class_heatmap, colores_heatmap, "Resultados - Variantes con MAF local > 0.01", "heatmap var1p.png")
```

# Heatmap con 3 clases pero sin variables con var = 0

```{r}
comparacion_3clases_conzv = readRDS("resultados_comparacion_3class_conzv_var1p")
```

```{r}
var1p_3class_conzv_heatmap = comparacion_3clases_conzv[,c(2,3,4,5,6,7,8,10)]
var1p_3class_conzv_heatmap
var1p_3class_conzv_heatmap = as.data.frame(var1p_3class_conzv_heatmap)
rownames(var1p_3class_conzv_heatmap) = var1p_3class_conzv_heatmap$Condiciones
var1p_3class_conzv_heatmap = var1p_3class_conzv_heatmap[,-8]
var1p_3class_conzv_heatmap = as.matrix(var1p_3class_conzv_heatmap)
```

```{r}
library(ggplot2)
library(grid)
library(pheatmap)



crear_heatmap <- function(matriz, color_palette, main_title, filename) {
    # Crear el heatmap
    heatmap <- pheatmap(matriz, 
                        cluster_rows = TRUE,
                        cluster_cols = TRUE,
                        treeheight_row = 0,    # Ocultar dendograma de filas
                        treeheight_col = 0,    # Ocultar dendograma de columnas
                        show_rownames = TRUE,
                        fontsize_col = 10,
                        angle_col = 90,        # Rotar nombres de columnas 45 grados
                        color = color_palette,
                        main = main_title)
    
    # Guardar el heatmap como PNG
    ggsave(filename, plot = heatmap, device = "png")
    
    # Retornar el objeto heatmap (opcional)
    return(heatmap)
}

colores_heatmap <- colorRampPalette(c("dodgerblue3","white", "firebrick1"))(50)
```

```{r}
crear_heatmap(var1p_3class_conzv_heatmap, colores_heatmap, "Resultados - Variantes con MAF local > 0.01 y varianza > 0 ", "heatmap var1p_conzv.png")

```

# Heatmap con 2 clases 

```{r}
comparacion_2clases = readRDS("resultados_comparacion_2class_var1p")
```

```{r}
var1p_2class_heatmap = comparacion_2clases[,c(2,3,4,6)]
var1p_2class_heatmap
var1p_2class_heatmap = as.data.frame(var1p_2class_heatmap)
rownames(var1p_2class_heatmap) = var1p_2class_heatmap$Condiciones
var1p_2class_heatmap = var1p_2class_heatmap[,-4]
var1p_2class_heatmap = as.matrix(var1p_2class_heatmap)
```

```{r}
library(ggplot2)
library(grid)
library(pheatmap)



crear_heatmap <- function(matriz, color_palette, main_title, filename) {
    # Crear el heatmap
    heatmap <- pheatmap(matriz, 
                        cluster_rows = TRUE,
                        cluster_cols = TRUE,
                        treeheight_row = 0,    # Ocultar dendograma de filas
                        treeheight_col = 0,    # Ocultar dendograma de columnas
                        show_rownames = TRUE,
                        fontsize_col = 16,
                        angle_col = 0,        # Rotar nombres de columnas 45 grados
                        color = color_palette,
                        main = main_title)
    
    # Guardar el heatmap como PNG
    ggsave(filename, plot = heatmap, device = "png")
    
    # Retornar el objeto heatmap (opcional)
    return(heatmap)
}

colores_heatmap <- colorRampPalette(c("white", "firebrick1"))(20)
```

```{r}
crear_heatmap(var1p_2class_heatmap, colores_heatmap, "Resultados - Variantes con MAF local > 0.01 y solo 2 clases", "heatmap var1p_2clases.png")

```
